apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  type: ClusterIP
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: {{ .Values.service.kafkaPort }}
      targetPort: 9092
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: 9644