apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-service.fullname" . }}
  labels:
    app: {{ include "app-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "app-service.fullname" . }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}