nameOverride: frontend

replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80

probes:
  enabled: true
  livenessPath: /
  readinessPath: /
  port: http

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
